name: Auto PR on push to feature branches

on:
  push:
    branches:
      - 'contact'
      - 'header'
      - 'footer'
      - 'login'
      - 'theme'
      - 'home'

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch origin branch
        run: git fetch origin ${{ github.ref_name }}

      - name: Checkout branch and create clean temp PR branch
        run: |
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          git branch -D auto-pr/${{ github.ref_name }} || true
          git checkout -b auto-pr/${{ github.ref_name }}

      - name: Delete remote auto-pr branch (if exists)
        run: |
          git push origin --delete auto-pr/${{ github.ref_name }} || true

      - name: Push clean auto-pr branch
        run: |
          git push origin auto-pr/${{ github.ref_name }}

      - name: Close old pull requests (if any)
        uses: peter-evans/close-pull@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Closing stale PR in favor of a new one."
          search: author:app/github-actions is:open is:pr head:auto-pr/${{ github.ref_name }} base:main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto-pr/${{ github.ref_name }}
          title: "Auto PR from '${{ github.ref_name }}' to 'main'"
          body: "This pull request was automatically created after a push to '${{ github.ref_name }}'."
          draft: false

